kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
data:
  05-multus.conf: |
      {"name": "multus-cni",
       "cniVersion":"0.1.0",
       "type": "multus",
       "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml",
       "delegates": [
       {
         "name": "cni0",
         "cniVersion":"0.3.1",
         "type": "calico",
         "etcd_endpoints": "ETCD_ENDPOINTS",
         "etcd_cert_file": "/etc/ssl/etcd/ssl/node.pem",
         "etcd_key_file": "/etc/ssl/etcd/ssl/node-key.pem",
         "etcd_ca_cert_file": "/etc/ssl/etcd/ssl/ca.pem",

         "log_level": "info",
         "masterplugin": true,
         "ipam": {
           "type": "calico-ipam",
           "assign_ipv4": "true",
           "ipv4_pools": ["10.233.64.0/18"]
         },
         "kubernetes": {
           "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml"
         }
       },{
         "name": "net0",
         "type": "macvlan",
         "master": "eth0",
         "ipam": {
           "type": "host-local",
           "subnet": "172.20.11.0/24"
           ### Note that this example range limits the whole cluster for 50 pods
           ### As 50 (250-200) IP addresses can be assigned only.
           ### Remove these lines (all comments including range) if will not use.
           #,"rangeStart": "172.20.11.200",
           #"rangeEnd": "172.20.11.250"
         }
       }]
      }
