kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
data:
  05-multus.conf: |
      {"name": "multus-cni",
       "cniVersion":"0.1.0",
       "type": "multus",
       "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml",
       "delegates": [
       {
         "name": "cni0",
         "cniVersion":"0.3.1",
         "type": "calico",
         "etcd_endpoints": "ETCD_ENDPOINTS",
         "etcd_cert_file": "/etc/calico/certs/cert.crt",
         "etcd_key_file": "/etc/calico/certs/key.pem",
         "etcd_ca_cert_file": "/etc/calico/certs/ca_cert.crt",

         "log_level": "info",
         "masterplugin": true,
         "ipam": {
           "type": "calico-ipam",
           "assign_ipv4": "true",
           "ipv4_pools": ["10.233.64.0/18"]
         },
         "kubernetes": {
           "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml"
         }
       }]
      }
