apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan0
spec:
  config: '{
    "type": "macvlan",
    "master": "eth0",
    "ipam": {
      "type": "host-local",
      "subnet": "172.16.10.0/24"
    }
  }'
