apiVersion: v1
kind: Namespace
metadata:
  name: keepalived-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-config
  namespace: keepalived-system
data:
  keepalived.conf: |
    vrrp_instance VI_1 {
        state MASTER
        interface _LB_IFACE_
        virtual_router_id 1
        priority 100
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass _LB_PASSWORD_
        }
        virtual_ipaddress {
            _LB_IP_
        }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: keepalived
  namespace: keepalived-system
  labels:
    app: keepalived
spec:
  selector:
    matchLabels:
      app: keepalived
  template:
    metadata:
      labels:
        app: keepalived
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      hostNetwork: true
      containers:
      - name: keepalived
        image: aialferov/keepalived:2.0.7
        args: ["-nl"]
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: config
          mountPath: /etc/keepalived
      volumes:
      - name: config
        configMap:
          name: keepalived-config
