apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: __K8S_VERSION__
apiServerCertSANs:
- "k8s.__CLUSTER__"
- "__LB_IP__"
controlPlaneEndpoint: "k8s.__CLUSTER__:6443"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://__IP__:2379"
      advertise-client-urls: "https://__IP__:2379"
      listen-peer-urls: "https://__IP__:2380"
      initial-advertise-peer-urls: "https://__IP__:2380"
      initial-cluster: "__ETCD_CLUSTER____HOSTNAME__=https://__IP__:2380"
      initial-cluster-state: "__ETCD_STATE__"
    serverCertSANs:
    - __HOSTNAME__
    - __IP__
    peerCertSANs:
    - __HOSTNAME__
    - __IP__
networking:
    podSubnet: "10.233.64.0/18"
    serviceSubnet: "10.233.0.0/18"
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1alpha3
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- "10.233.0.10"
