---
- hosts: all
  gather_facts: False
  tasks:
  - name: SSH keys add
    when: ssh_keys is defined
    authorized_key:
      user: "{{ ansible_user }}"
      state: present
      key: "{{ item }}"
    with_items: "{{ ssh_keys }}"
  - name: SSH keys delete
    when: no_ssh_keys is defined
    authorized_key:
      user: "{{ ansible_user }}"
      state: absent
      key: "{{ item }}"
    with_items: "{{ no_ssh_keys }}"
