apiVersion: v1
kind: ConfigMap
metadata:
  name: keepalived-config
  namespace: keepalived-system
data:
  keepalived.conf: |
    vrrp_instance VI_1 {
        state MASTER
        interface eth0
        virtual_router_id 1
        priority 100
        advert_int 1
        authentication {
            auth_type PASS
            auth_pass 6iYnj%+Va2x
        }
        virtual_ipaddress {
            10.9.8.10
        }
    }
